# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iXkBUsrBMvcRGu31bpPJWj0tsLP4XjME
"""

import time
from w1thermsensor import W1ThermSensor
import RPi.GPIO as GPIO
import board
import busio

DELTA_T = 0.55    # Tolerance on what's considered steady state, +- degrees C (=1 deg F)
SP = 27

GPIO.setmode(GPIO.BCM)
H = 12 # Heater
MP = 16 # Main pump
GPIO.setup(H, GPIO.OUT)
GPIO.setup(MP, GPIO.OUT)
sensor = W1ThermSensor()

def readtemp():     # Return current_temp
  return sensor.get_temperature()

def setHeater(state): # Turns on/off the heater
  GPIO.output(H,state)

def writeData(data):
  output_file = open('temp_test.txt', 'a')
  output_file.write(str(data)+'\n')
  output_file.close()

GPIO.output(MP,1)

while(True):
  data = readtemp()
  writeData(data)
  if (data<(SP-DELTA_T)):
    setHeater(1)
  elif (data>(SP+DELTA_T)):
    setHeater(0)
  sleep(60)